service: my-serverless-service

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1

  package:
  exclude:
    - ./**
  include:
    - lambdas/**
    - node_modules/some-required-module/**

functions:
  getTodos:
    handler: lambdas/todos.getTodos
    events:
      - http:
          path: todos
          method: get

  createTodo:
    handler: lambdas/todos.createTodo
    events:
      - http:
          path: todos
          method: post

  deleteTodo:
    handler: lambdas/todos.deleteTodo
    events:
      - http:
          path: todos/{todoId}
          method: delete
